
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async changeBinding(id: string, binding: string) : Promise<Result<BindingResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_binding", { id, binding }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resetBinding(id: string) : Promise<Result<BindingResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reset_binding", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePttSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_ptt_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Toggle the "tap to lock a hold recording hands-free" gesture. When off,
 * holding the hotkey never arms the lock-key watcher, so a stray tap can't
 * convert an in-progress recording to hands-free.
 */
async changeTapToLockSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_tap_to_lock_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set the key that a tap converts a hold recording to hands-free (the "Tap to
 * Lock" gesture). Accepts a modifier ("shift", "ctrl", "alt", "super"/"cmd")
 * or a plain key name ("tab", "f8", …). Persisted; takes effect on the next
 * recording (the watcher reads it fresh each time it arms).
 */
async changeTapToLockKeySetting(key: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_tap_to_lock_key_setting", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAudioFeedbackSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_audio_feedback_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAudioFeedbackVolumeSetting(volume: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_audio_feedback_volume_setting", { volume }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeSoundThemeSetting(theme: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_sound_theme_setting", { theme }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeThemeSetting(theme: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_theme_setting", { theme }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeUiTextSizeSetting(size: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_ui_text_size_setting", { size }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeStartHiddenSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_start_hidden_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAutostartSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_autostart_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeTranslateToEnglishSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_translate_to_english_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeSelectedLanguageSetting(language: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_selected_language_setting", { language }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeOverlayPositionSetting(position: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_overlay_position_setting", { position }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeDebugModeSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_debug_mode_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeWordCorrectionThresholdSetting(threshold: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_word_correction_threshold_setting", { threshold }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeExtraRecordingBufferSetting(ms: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_extra_recording_buffer_setting", { ms }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePasteDelayMsSetting(ms: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_paste_delay_ms_setting", { ms }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePasteMethodSetting(method: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_paste_method_setting", { method }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAvailableTypingTools() : Promise<string[]> {
    return await TAURI_INVOKE("get_available_typing_tools");
},
async changeTypingToolSetting(tool: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_typing_tool_setting", { tool }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeExternalScriptPathSetting(path: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_external_script_path_setting", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeClipboardHandlingSetting(handling: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_clipboard_handling_setting", { handling }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAutoSubmitSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_auto_submit_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAutoSubmitKeySetting(key: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_auto_submit_key_setting", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getPostProcessReadiness() : Promise<PostProcessReadiness> {
    return await TAURI_INVOKE("get_post_process_readiness");
},
async changePostProcessEnabledSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_post_process_enabled_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Make an on-device model the AI-cleanup engine, keeping the prompt layer
 * coherent with it.
 * 
 * One command rather than the three round-trips the UI used to make, because
 * the three have to agree: the provider must be the built-in engine, the model
 * must be assigned to it, and the selected cleanup prompt has to suit the model.
 * That last part is the reason this exists at all — SpeakoFlow Mini is trained
 * on one short prompt and is measurably worse when handed the long
 * general-purpose one, and the long prompt is what a general chat model needs to
 * stay on task. Getting that pairing wrong looks like "the model is bad", so the
 * app pairs them.
 * 
 * Only the two *shipped* prompts are ever swapped. Anything the user selected or
 * wrote themselves is left exactly as it is — a silent switch away from
 * someone's own prompt would be worse than a suboptimal default.
 */
async setCleanupLocalModel(modelId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_cleanup_local_model", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Restore a shipped cleanup prompt to the exact text the app ships.
 * 
 * Needed because the SpeakoFlow Mini prompt is editable like any other: a user
 * who experiments with it (or pastes over it) otherwise has no way back to the
 * text the fine-tune was actually trained on, and no way to know they have
 * drifted from it.
 */
async restorePostProcessPrompt(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("restore_post_process_prompt", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePostProcessToneSetting(tone: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_post_process_tone_setting", { tone }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addPostProcessCustomTone(name: string, instruction: string) : Promise<Result<CustomPostProcessTone, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_post_process_custom_tone", { name, instruction }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updatePostProcessCustomTone(id: string, name: string, instruction: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_post_process_custom_tone", { id, name, instruction }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deletePostProcessCustomTone(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_post_process_custom_tone", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePostProcessTimeoutSetting(seconds: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_post_process_timeout_setting", { seconds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeExperimentalEnabledSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_experimental_enabled_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePostProcessBaseUrlSetting(providerId: string, baseUrl: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_post_process_base_url_setting", { providerId, baseUrl }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePostProcessApiKeySetting(providerId: string, apiKey: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_post_process_api_key_setting", { providerId, apiKey }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changePostProcessModelSetting(providerId: string, model: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_post_process_model_setting", { providerId, model }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setPostProcessProvider(providerId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_post_process_provider", { providerId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async fetchPostProcessModels(providerId: string) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_post_process_models", { providerId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addPostProcessPrompt(name: string, prompt: string) : Promise<Result<LLMPrompt, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_post_process_prompt", { name, prompt }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updatePostProcessPrompt(id: string, name: string, prompt: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_post_process_prompt", { id, name, prompt }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deletePostProcessPrompt(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_post_process_prompt", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setPostProcessSelectedPrompt(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_post_process_selected_prompt", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateCustomWords(words: string[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_custom_words", { words }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeSpokenEmojisEnabledSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_spoken_emojis_enabled_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeReplacementsEnabledSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_replacements_enabled_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateTextReplacements(replacements: Replacement[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_text_replacements", { replacements }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Writes the given contents to a user-chosen path. The path comes from the
 * frontend's native "save" dialog; file I/O is done here (rather than via the
 * JS fs plugin) so the user can export anywhere, not just inside `$APPDATA`.
 */
async exportTextReplacements(path: string, contents: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_text_replacements", { path, contents }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Reads a user-chosen file (selected via the native "open" dialog) and returns
 * its contents as a string for the frontend to parse.
 */
async importTextReplacements(path: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_text_replacements", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Temporarily unregister a binding while the user is editing it in the UI.
 * This avoids firing the action while keys are being recorded.
 */
async suspendBinding(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("suspend_binding", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Re-register the binding after the user has finished editing.
 */
async resumeBinding(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resume_binding", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeMuteWhileRecordingSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_mute_while_recording_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAppendTrailingSpaceSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_append_trailing_space_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeLazyStreamCloseSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_lazy_stream_close_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeLiveTranscriptionEnabledSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_live_transcription_enabled_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Toggle the opt-in live-transcription window: when on (and live transcription
 * is enabled), the recording overlay grows into a readable card showing the
 * running committed + tentative transcript; when off, the overlay stays the
 * compact pill. Off by default.
 */
async changeLiveTranscriptionWindowEnabledSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_live_transcription_window_enabled_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set the recording (dictation) overlay style: none / minimal / live (or auto
 * to follow the model). Picking Live also enables streaming transcription so
 * the running transcript can actually appear; Minimal/None turn it back off.
 * `auto` leaves the streaming toggle alone (the show path resolves per model).
 */
async changeOverlayStyleSetting(style: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_overlay_style_setting", { style }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeAppLanguageSetting(language: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_app_language_setting", { language }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeUpdateChecksSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_update_checks_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Change the keyboard implementation with runtime switching.
 * This will unregister all shortcuts from the old implementation,
 * validate shortcuts for the new implementation (resetting invalid ones to defaults),
 * and register them with the new implementation.
 */
async changeKeyboardImplementationSetting(implementation: string) : Promise<Result<ImplementationChangeResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_keyboard_implementation_setting", { implementation }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the current keyboard implementation
 */
async getKeyboardImplementation() : Promise<string> {
    return await TAURI_INVOKE("get_keyboard_implementation");
},
async changeShowTrayIconSetting(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_show_tray_icon_setting", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set what closing the main window does: minimize to the tray (default) or
 * fully quit the app. The `Quit` branch reuses the same `app.exit(0)` path as
 * the tray "Quit" item (see the `CloseRequested` handler in `lib.rs`). See
 * GitHub issue #6.
 */
async changeCloseBehaviorSetting(behavior: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_close_behavior_setting", { behavior }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeWhisperAcceleratorSetting(accelerator: WhisperAcceleratorSetting) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_whisper_accelerator_setting", { accelerator }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeOrtAcceleratorSetting(accelerator: OrtAcceleratorSetting) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_ort_accelerator_setting", { accelerator }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async changeWhisperGpuDevice(device: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("change_whisper_gpu_device", { device }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Return which accelerators and GPU devices are available for this build.
 * 
 * First-call cost is dominated by enumerating GPU devices through the
 * whisper.cpp Metal/Vulkan backend, which loads dynamic libraries and
 * probes hardware. Run it on the blocking pool so the webview thread
 * stays responsive — see also the startup pre-warm in `lib.rs`.
 */
async getAvailableAccelerators() : Promise<AvailableAccelerators> {
    return await TAURI_INVOKE("get_available_accelerators");
},
/**
 * Start key recording mode
 */
async startHandyKeysRecording(bindingId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_handy_keys_recording", { bindingId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stop key recording mode
 */
async stopHandyKeysRecording() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_handy_keys_recording") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async triggerUpdateCheck() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("trigger_update_check") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async showMainWindowCommand() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_main_window_command") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelOperation() : Promise<void> {
    await TAURI_INVOKE("cancel_operation");
},
/**
 * Finish the current recording right now and run the normal transcribe
 * pipeline on it. This is the "done" tick on the recording overlay — the
 * keyboard-free way to end a hands-free (tap-to-lock or toggle) recording.
 * Unlike `cancel_operation`, the captured audio is kept and transcribed.
 * No-op when nothing is recording.
 */
async commitRecording() : Promise<void> {
    await TAURI_INVOKE("commit_recording");
},
/**
 * Start/stop a plain dictation recording programmatically, for in-app
 * "dictate into this field" mic buttons (e.g. a profile's instruction box).
 * Hands-free toggle: the first call starts recording, the second stops it.
 * Because this recording uses the
 * `"in-app"` source, its transcript is delivered to the webview via the
 * `dictation-transcript` event (the field listens for it) instead of being
 * pasted into the focused OS window — reliable and clipboard-free. No-op if the
 * coordinator isn't ready yet.
 */
async toggleDictation() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_dictation") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isPortable() : Promise<boolean> {
    return await TAURI_INVOKE("is_portable");
},
async getAppDirPath() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_app_dir_path") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAppSettings() : Promise<Result<AppSettings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_app_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDefaultSettings() : Promise<Result<AppSettings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_default_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Best-effort total physical system memory, in whole gibibytes (rounded to
 * the nearest). Used by onboarding to suggest a local assistant model that
 * comfortably fits the machine. Returns 0 when the amount can't be determined
 * so the caller can fall back to a safe default.
 */
async getSystemMemoryGb() : Promise<number> {
    return await TAURI_INVOKE("get_system_memory_gb");
},
async getLogDirPath() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_log_dir_path") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setLogLevel(level: LogLevel) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_log_level", { level }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openRecordingsFolder() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_recordings_folder") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openLogDir() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_log_dir") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openAppDataDir() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_app_data_dir") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check if Apple Intelligence is available on this device.
 * Called by the frontend when the user selects Apple Intelligence provider.
 */
async checkAppleIntelligenceAvailable() : Promise<boolean> {
    return await TAURI_INVOKE("check_apple_intelligence_available");
},
/**
 * Try to initialize Enigo (keyboard/mouse simulation).
 * On macOS, this will return an error if accessibility permissions are not granted.
 */
async initializeEnigo() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("initialize_enigo") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Initialize keyboard shortcuts.
 * On macOS, this should be called after accessibility permissions are granted.
 * This is idempotent - calling it multiple times is safe.
 */
async initializeShortcuts() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("initialize_shortcuts") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAvailableModels() : Promise<Result<ModelInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_available_models") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getModelInfo(modelId: string) : Promise<Result<ModelInfo | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_model_info", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async downloadModel(modelId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_model", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteModel(modelId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_model", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelDownload(modelId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_download", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setActiveModel(modelId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_active_model", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getCurrentModel() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_current_model") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTranscriptionModelStatus() : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_transcription_model_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isModelLoading() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("is_model_loading") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async hasAnyModelsAvailable() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("has_any_models_available") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async hasAnyModelsOrDownloads() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("has_any_models_or_downloads") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Search the Hugging Face Hub for GGUF language-model repositories.
 * 
 * An empty query returns the most-downloaded GGUF repos as a default browse
 * list. Used by the "Add custom model" flow in the Models tab.
 */
async searchHuggingfaceModels(query: string) : Promise<Result<HfModelSummary[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_huggingface_models", { query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List the downloadable `.gguf` files (model weights and vision projectors)
 * in a Hugging Face repo, with sizes, so the user can pick a quantization.
 */
async listHuggingfaceGgufFiles(repoId: string) : Promise<Result<HfRepoFiles, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_huggingface_gguf_files", { repoId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Register a user-chosen GGUF model from the Hub as a custom local LLM and
 * persist it. The frontend then downloads it via the normal `download_model`
 * command. `mmproj_filename` (optional) is the repo's vision projector.
 */
async addCustomLlmModel(repoId: string, filename: string, sizeMb: number, mmprojFilename: string | null) : Promise<Result<ModelInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_custom_llm_model", { repoId, filename, sizeMb, mmprojFilename }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Register models the user already has on disk, from paths they picked.
 * 
 * Nothing is copied or moved — each entry points at the file where it lives.
 */
async addLocalModels(paths: string[]) : Promise<Result<LocalModelImport, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_local_models", { paths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Link a folder of existing models and scan it. Returns how many were found.
 */
async addModelFolder(path: string) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_model_folder", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Unlink a folder. Its models leave the catalog; the files stay where they are.
 */
async removeModelFolder(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_model_folder", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * The currently linked model folders, in the order they were added.
 */
async getModelFolders() : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_model_folders") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Re-scan every linked folder and re-check every registered local file.
 * 
 * The manual counterpart to the scan that runs at startup, for when the user
 * has just added a model to a linked folder or reconnected a drive. Returns the
 * total number of local models now registered.
 */
async rescanLocalModels() : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rescan_local_models") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Current status of the built-in LLM engine (running, which model, whether an
 * engine binary is present, etc.).
 */
async getLocalLlmStatus() : Promise<Result<LocalLlmStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_local_llm_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Start (or switch) the built-in engine to serve `model_id`. Resolves once the
 * engine is accepting requests.
 */
async startLocalLlm(modelId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_local_llm", { modelId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stop the built-in engine, freeing its memory.
 */
async stopLocalLlm() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_local_llm") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set the context window (in tokens) for the built-in local LLM engine.
 * 
 * The value is clamped to a safe range and only read when the engine starts,
 * so any running engine is stopped here; the next post-processing turn
 * restarts it with the new size. External providers (Ollama / LM Studio /
 * cloud) are unaffected — they manage their own context.
 */
async setLocalLlmContextSize(size: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_local_llm_context_size", { size }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set the idle timeout after which the built-in local LLM engine is unloaded
 * to free RAM/VRAM. `Never` keeps it resident once started; shorter values
 * free memory sooner at the cost of a reload on the next use (largely hidden
 * by prewarm-on-record). Only the built-in engine is affected — external
 * providers (Ollama / LM Studio / cloud) manage their own lifecycle.
 */
async setLocalLlmUnloadTimeout(timeout: ModelUnloadTimeout) : Promise<void> {
    await TAURI_INVOKE("set_local_llm_unload_timeout", { timeout });
},
async updateMicrophoneMode(alwaysOn: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_microphone_mode", { alwaysOn }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getMicrophoneMode() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_microphone_mode") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getWindowsMicrophonePermissionStatus() : Promise<WindowsMicrophonePermissionStatus> {
    return await TAURI_INVOKE("get_windows_microphone_permission_status");
},
async openMicrophonePrivacySettings() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_microphone_privacy_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAvailableMicrophones() : Promise<Result<AudioDevice[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_available_microphones") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSelectedMicrophone(deviceName: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_selected_microphone", { deviceName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSelectedMicrophone() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_selected_microphone") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAvailableOutputDevices() : Promise<Result<AudioDevice[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_available_output_devices") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSelectedOutputDevice(deviceName: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_selected_output_device", { deviceName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSelectedOutputDevice() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_selected_output_device") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async playTestSound(soundType: string) : Promise<void> {
    await TAURI_INVOKE("play_test_sound", { soundType });
},
async checkCustomSounds() : Promise<CustomSounds> {
    return await TAURI_INVOKE("check_custom_sounds");
},
async setClamshellMicrophone(deviceName: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_clamshell_microphone", { deviceName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getClamshellMicrophone() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_clamshell_microphone") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async isRecording() : Promise<boolean> {
    return await TAURI_INVOKE("is_recording");
},
async setModelUnloadTimeout(timeout: ModelUnloadTimeout) : Promise<void> {
    await TAURI_INVOKE("set_model_unload_timeout", { timeout });
},
async getModelLoadStatus() : Promise<Result<ModelLoadStatus, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_model_load_status") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async unloadModelManually() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unload_model_manually") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getHistoryEntries(cursor: number | null, limit: number | null) : Promise<Result<PaginatedHistory, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_history_entries", { cursor, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async toggleHistoryEntrySaved(id: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_history_entry_saved", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAudioFilePath(fileName: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_audio_file_path", { fileName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteHistoryEntry(id: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_history_entry", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async retryHistoryEntryTranscription(id: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("retry_history_entry_transcription", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateHistoryLimit(limit: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_history_limit", { limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateRecordingRetentionPeriod(period: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_recording_retention_period", { period }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Switch the active profile. Errors if the id no longer exists.
 */
async setActiveProfile(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_active_profile", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Replace the whole profile list. Add / edit / reorder / duplicate / delete
 * all funnel through here (like text replacements), which keeps the UI simple.
 * Enforces the invariants: the non-deletable `default` profile must remain,
 * the list can't be empty, ids must be unique, and the active id must still
 * resolve.
 */
async setProfiles(profiles: Profile[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_profiles", { profiles }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Load an image file as a small avatar data URL (downscaled to 256px so it
 * stays compact inside the settings file).
 */
async readProfileAvatar(path: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_profile_avatar", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Import a profile from a JSON file on disk (path chosen via the UI's file
 * dialog). The imported profile always gets a fresh id and is never marked
 * built-in, so it can't clobber a built-in or the non-deletable default.
 */
async importProfile(path: string) : Promise<Result<Profile, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_profile", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Export a single profile to a JSON file on disk (path chosen via the UI's
 * save dialog).
 */
async exportProfile(id: string, path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_profile", { id, path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Reset a built-in profile to the version shipped with the app. Custom
 * profiles have no shipped default, so this only works on built-in ids. This
 * is the "reload" for a built-in whose instructions you edited (or wiped) and
 * want back.
 */
async restoreBuiltinProfile(id: string) : Promise<Result<Profile, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("restore_builtin_profile", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Re-add any built-in profiles the user deleted, leaving their custom profiles
 * and their edits to still-present built-ins untouched. Returns how many were
 * restored (0 if none were missing).
 */
async restoreMissingBuiltinProfiles() : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("restore_missing_builtin_profiles") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Turn the personal-memory feature on or off. Off by default.
 */
async setMemoryEnabled(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_memory_enabled", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Set how much memory is injected per cleanup pass (the budget dial).
 */
async setMemoryDetail(detail: MemoryDetail) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_memory_detail", { detail }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Toggle incognito: while on, dictations are neither personalized from memory
 * nor learned from.
 */
async setMemoryIncognito(incognito: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_memory_incognito", { incognito }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Turn automatic learning from past dictations on or off. Off by default, so
 * memory holds only what the user entered or explicitly asked for.
 */
async setMemoryAutoLearn(enabled: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_memory_auto_learn", { enabled }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Replace the always-on "About You" summary (user-edited in Settings).
 */
async setMemoryAboutYou(text: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_memory_about_you", { text }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Add a user-authored note (explicit → high confidence). Returns the new note.
 */
async addMemoryNote(text: string) : Promise<Result<MemoryNote, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_memory_note", { text }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Edit an existing note's text (keeps it user-owned; bumps its date).
 */
async updateMemoryNote(id: string, text: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_memory_note", { id, text }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a single note by id.
 */
async deleteMemoryNote(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_memory_note", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Wipe the entire personal memory (summary + all notes). Does not change the
 * enabled toggle.
 */
async clearMemory() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_memory") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Export the whole memory to a JSON file on disk (path chosen via the UI's
 * save dialog). Your data, in a portable, human-readable file.
 */
async exportMemory(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_memory", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Import memory from a JSON file (path chosen via the UI's file dialog),
 * replacing the current memory. Sensitive/oversized entries are filtered out
 * on the way in.
 */
async importMemory(path: string) : Promise<Result<UserMemory, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_memory", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Learn from recent dictations right now (the "Update memory from my
 * dictations" button). Reads the last [`DISTILL_HISTORY_LIMIT`] history
 * entries and runs the extraction pass immediately, so the user can see it
 * work instead of waiting for it to happen in the background.
 * 
 * Deliberately explicit: automatic learning is off by default (see
 * `memory_auto_learn`), which makes this button the only path into memory
 * besides typing a note by hand.
 */
async distillMemoryNow() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("distill_memory_now") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stub implementation for non-macOS platforms
 * Always returns false since laptop detection is macOS-specific
 */
async isLaptop() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("is_laptop") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
historyUpdatePayload: HistoryUpdatePayload
}>({
historyUpdatePayload: "history-update-payload"
})

/** user-defined constants **/



/** user-defined types **/

/**
 * The container-level `#[serde(default)]` (backed by the `Default` impl below,
 * which returns `get_default_settings()`) guarantees every field — including
 * ones added in the future — falls back to its default value when missing from
 * a stored settings object, so a partial store can never fail the whole load.
 * Field-level `#[serde(default = "...")]` attributes still take precedence
 * where present. Together with `salvage_settings`, this means one missing or
 * broken field can never reset the rest of the user's configuration
 * (backport of Handy #1631).
 */
export type AppSettings = { bindings: Partial<{ [key in string]: ShortcutBinding }>; push_to_talk: boolean; 
/**
 * While a push-to-talk (hold) recording is active, a quick tap of the
 * configured lock key (see `tap_to_lock_key`) converts it to hands-free
 * (locked) mode so you can let go of the hotkey and keep talking. On by
 * default; turn off if a stray tap keeps locking your recordings. Only
 * relevant while push-to-talk is on.
 */
tap_to_lock?: boolean; 
/**
 * The key you tap (while holding a push-to-talk recording) to lock it
 * hands-free. Defaults to Shift. Pick a key that isn't part of your record
 * shortcut and that you won't press by accident. Accepts a modifier
 * ("shift", "ctrl", "alt", "super"/"cmd") or a plain key name ("tab", "f8",
 * …). Only relevant while push-to-talk and Tap to Lock are on.
 */
tap_to_lock_key?: string; audio_feedback: boolean; audio_feedback_volume?: number; sound_theme?: SoundTheme; start_hidden?: boolean; autostart_enabled?: boolean; update_checks_enabled?: boolean; selected_model?: string; always_on_microphone?: boolean; 
/**
 * Opt-in live/streaming transcription: while recording, feed audio into a
 * streaming transcriber and paste the merged running result at the end
 * (with the batch `transcribe()` path as the fallback). Off by default —
 * when off, dictation behaves exactly as before.
 */
live_transcription_enabled?: boolean; 
/**
 * Opt-in live-transcription window: while streaming dictation is running,
 * enlarge the recording overlay into a readable card that shows the
 * running committed + tentative transcript, instead of the compact pill.
 * Off by default. Only takes effect when `live_transcription_enabled` is
 * also on (there's no live text to show otherwise); when off, the overlay
 * stays the compact pill exactly as before.
 */
live_transcription_window_enabled?: boolean; selected_microphone?: string | null; clamshell_microphone?: string | null; selected_output_device?: string | null; translate_to_english?: boolean; selected_language?: string; overlay_position?: OverlayPosition; 
/**
 * Recording (dictation) overlay style: Auto/None/Minimal/Live. Auto follows
 * the model's live-streaming support (Live if supported, else Minimal).
 */
overlay_style?: OverlayStyle; debug_mode?: boolean; log_level?: LogLevel; custom_words?: string[]; 
/**
 * Folders the user keeps their own models in. Each is scanned recursively
 * and every `.gguf` / Whisper `.bin` found is registered as a catalog entry
 * pointing at its real location — nothing is copied into the app's models
 * directory. Any number of folders can be linked, which is the point: model
 * collections are routinely spread across an internal drive, an external
 * one, and a fine-tuning output directory.
 * 
 * Stored as absolute paths. Missing folders (unplugged drive) are skipped
 * with a warning rather than dropped, so the link survives a reconnect.
 */
model_folders?: string[]; 
/**
 * Convert explicit spoken commands such as `happy emoji` into their
 * Unicode emoji during ordinary dictation. This pass is fully local and
 * deterministic; it is opt-in so the same words remain literal by default.
 */
spoken_emojis_enabled?: boolean; 
/**
 * Master switch for the deterministic text-replacements pass.
 */
replacements_enabled?: boolean; 
/**
 * Ordered list of find/replace rules applied after LLM post-processing.
 */
text_replacements?: Replacement[]; model_unload_timeout?: ModelUnloadTimeout; 
/**
 * Idle timeout after which the built-in local LLM engine (llama.cpp
 * sidecar) is unloaded to free RAM/VRAM. Mirrors `model_unload_timeout`
 * but applies to the LLM used for post-processing and the assistant.
 */
local_llm_unload_timeout?: ModelUnloadTimeout; 
/**
 * How long the **AI-cleanup** engine stays loaded after its last use.
 * 
 * Separate from `local_llm_unload_timeout` on purpose: cleanup runs on
 * every dictation with a small model, while the assistant's model is larger
 * and used in bursts. Keeping cleanup resident for longer costs a few
 * hundred MB of RAM and no CPU at all (an idle engine does no work), and it
 * removes the reload from the dictation path entirely.
 */
post_process_unload_timeout?: ModelUnloadTimeout; word_correction_threshold?: number; history_limit?: number; recording_retention_period?: RecordingRetentionPeriod; paste_method?: PasteMethod; clipboard_handling?: ClipboardHandling; auto_submit?: boolean; auto_submit_key?: AutoSubmitKey; post_process_enabled?: boolean; post_process_provider_id?: string; post_process_providers?: PostProcessProvider[]; post_process_api_keys?: SecretMap; post_process_models?: Partial<{ [key in string]: string }>; post_process_prompts?: LLMPrompt[]; post_process_selected_prompt_id?: string | null; post_process_tone?: PostProcessTone; 
/**
 * User-created writing styles. Built-ins remain code-defined/localized and
 * are selected by their stable IDs.
 */
post_process_custom_tones?: CustomPostProcessTone[]; 
/**
 * Stable built-in tone ID or a `CustomPostProcessTone.id`. Optional only so
 * old stores can migrate from `post_process_tone` without losing choice.
 */
post_process_selected_tone_id?: string | null; post_process_timeout_secs?: number; 
/**
 * The cloud provider the user last had selected for AI cleanup, remembered
 * so the device ⇄ cloud switch can put it back.
 * 
 * `post_process_provider_id` is a single slot: choosing "On my device"
 * overwrites it with `builtin` and destroys the record of which cloud
 * provider was configured. This used to be React state, which meant the
 * choice survived a toggle but not a navigation away from the page — the
 * user came back, switched to cloud, and landed on some other provider with
 * their model selection apparently gone.
 */
post_process_last_cloud_provider_id?: string | null; mute_while_recording?: boolean; append_trailing_space?: boolean; app_language?: string; experimental_enabled?: boolean; lazy_stream_close?: boolean; keyboard_implementation?: KeyboardImplementation; show_tray_icon?: boolean; close_behavior?: CloseBehavior; paste_delay_ms?: number; typing_tool?: TypingTool; external_script_path: string | null; custom_filler_words?: string[] | null; whisper_accelerator?: WhisperAcceleratorSetting; ort_accelerator?: OrtAcceleratorSetting; whisper_gpu_device?: number; extra_recording_buffer_ms?: number; 
/**
 * Context window (in tokens) the built-in local LLM engine launches with.
 * Applied when the engine starts; ignored by external providers
 * (Ollama / LM Studio / cloud), which manage their own context.
 */
local_llm_context_size?: number; 
/**
 * Selectable dictation profiles: each bundles a cleanup prompt, tone,
 * extra instructions, and whether memory is injected. Seeded with
 * built-ins on first run (see `default_profiles`).
 */
profiles?: Profile[]; 
/**
 * Id of the currently active profile (defaults to `"default"`).
 */
active_profile_id?: string; 
/**
 * Whether SpeakoFlow keeps a local, personal memory of the user (an
 * always-on "About You" summary plus durable notes) and injects the
 * relevant parts into AI cleanup. Off by default; everything stays on this
 * device and is fully user-editable in Settings → Memory.
 */
memory_enabled?: boolean; 
/**
 * The user's personal memory: a short always-on summary + durable notes.
 */
memory?: UserMemory; 
/**
 * How much memory to inject per cleanup pass (a character-budget dial).
 * Light keeps only the summary; Balanced adds a few relevant notes;
 * Detailed adds more.
 */
memory_detail?: MemoryDetail; 
/**
 * When true, memory is "incognito": neither injected into cleanup nor
 * learned from new dictations. A quick switch so private dictation leaves
 * no trace in memory.
 */
memory_incognito?: boolean; 
/**
 * Whether SpeakoFlow may distill new memory notes from past dictations
 * on its own. Off by default: with it off, memory only ever holds what the
 * user typed in Settings → Memory or asked for explicitly.
 */
memory_auto_learn?: boolean; theme?: Theme; ui_text_size?: UiTextSize; 
/**
 * Remembered main-window size in logical pixels, saved when the user
 * resizes/closes the window and restored (clamped to the current monitor)
 * on the next launch. `None` until first set — the code then falls back to
 * a sensible content-fitting default. Only the size is remembered, not the
 * position, so the window can't reopen off-screen after a monitor change.
 */
main_window_width?: number | null; main_window_height?: number | null }
export type AudioDevice = { index: string; name: string; is_default: boolean }
export type AutoSubmitKey = "enter" | "ctrl_enter" | "cmd_enter"
export type AvailableAccelerators = { whisper: string[]; ort: string[]; gpu_devices: GpuDeviceOption[]; 
/**
 * transcribe.cpp compute devices (`transcribe_cpp::devices()`), added in
 * Session 2. Informational for now (proves the GPU is visible to the new
 * engine); the transcribe.cpp backend reuses the existing whisper
 * GPU-device dial, so there is no separate device setting.
 */
transcribe_cpp_devices: GpuDeviceOption[] }
export type BindingResponse = { success: boolean; binding: ShortcutBinding | null; error: string | null }
/**
 * Case transform applied to the output of a text replacement rule.
 */
export type Capitalization = 
/**
 * Leave the replacement text as written.
 */
"none" | 
/**
 * UPPERCASE the whole replacement.
 */
"uppercase" | 
/**
 * lowercase the whole replacement.
 */
"lowercase" | 
/**
 * Capitalize the first character of the replacement.
 */
"capitalize"
export type ClipboardHandling = "dont_modify" | "copy_to_clipboard"
/**
 * What happens when the user closes the main window.
 * 
 * `MinimizeToTray` (the default) preserves the long-standing behavior: the
 * window hides and the app keeps running in the tray/menubar so global
 * hotkeys stay live. `Quit` fully exits the process on window close, for
 * users who don't want a background process (see GitHub issue #6).
 */
export type CloseBehavior = "minimize_to_tray" | "quit"
/**
 * A user-created writing style for cleanup. It is deliberately separate from
 * `LLMPrompt`: cleanup prompts define what corrections happen; tone presets
 * define how the resulting wording should sound.
 */
export type CustomPostProcessTone = { id: string; name: string; instruction: string }
export type CustomSounds = { start: boolean; stop: boolean }
export type EngineType = "Whisper" | "Parakeet" | "Moonshine" | "MoonshineStreaming" | "SenseVoice" | "GigaAM" | "Canary" | "Cohere" | 
/**
 * Native transcribe.cpp (ggml/GGUF) engine, added side-by-side with
 * transcribe-rs for the new single-file GGUF models (batch in Session 2,
 * real streaming in Session 4). This IS a transcription engine.
 */
"TranscribeCpp" | 
/**
 * Local large-language-model engine (GGUF served via the bundled
 * llama.cpp sidecar). Not a transcription engine.
 */
"LlamaCpp" | 
/**
 * Local text-to-speech engine (Kokoro, runs in the assistant webview).
 * Not a transcription engine.
 */
"Kokoro"
/**
 * One compute device. `Deserialize` is needed by the Linux out-of-process
 * probe, which parses this back out of the child's JSON.
 */
export type GpuDeviceOption = { id: number; name: string; kind: string; total_vram_mb: number }
/**
 * A single `.gguf` file inside a repo.
 */
export type HfGgufFile = { 
/**
 * File name within the repo, e.g. `Qwen_Qwen3.5-4B-Q4_K_M.gguf`.
 */
filename: string; 
/**
 * File size in bytes (from the Hub tree listing).
 */
size_bytes: number; 
/**
 * Short quantization label extracted from the filename, e.g. `Q4_K_M`.
 */
quant: string }
/**
 * A single repo returned by a Hub model search.
 */
export type HfModelSummary = { 
/**
 * Canonical repo id, e.g. `bartowski/Qwen_Qwen3.5-4B-GGUF`.
 */
id: string; 
/**
 * Number of likes (popularity signal shown in the UI).
 */
likes: number; 
/**
 * Number of downloads (popularity signal shown in the UI).
 */
downloads: number; 
/**
 * Whether the repo looks like a multimodal/vision model (so the UI can
 * hint that a projector will be downloaded for image support).
 */
is_vision: boolean }
/**
 * The downloadable GGUF assets in a repo, split into model weights and vision
 * projectors (`mmproj-*.gguf`).
 */
export type HfRepoFiles = { repo_id: string; 
/**
 * Model weight files the user can pick from (one per quantization).
 */
gguf_files: HfGgufFile[]; 
/**
 * Companion vision projectors, if the repo is multimodal.
 */
mmproj_files: HfGgufFile[] }
export type HistoryEntry = { id: number; file_name: string; timestamp: number; saved: boolean; title: string; transcription_text: string; post_processed_text: string | null; post_process_prompt: string | null; post_process_requested: boolean }
export type HistoryUpdatePayload = { action: "added"; entry: HistoryEntry } | { action: "updated"; entry: HistoryEntry } | { action: "deleted"; id: number } | { action: "toggled"; id: number }
/**
 * Result of changing keyboard implementation
 */
export type ImplementationChangeResult = { success: boolean; 
/**
 * List of binding IDs that were reset to defaults due to incompatibility
 */
reset_bindings: string[] }
export type KeyboardImplementation = "tauri" | "handy_keys"
export type LLMPrompt = { id: string; name: string; prompt: string }
export type LocalLlmStatus = { 
/**
 * Whether the engine process is currently running.
 */
running: boolean; 
/**
 * The model id the engine is currently serving (if any).
 */
model_id: string | null; 
/**
 * Whether an engine binary could be located on this machine.
 */
engine_present: boolean; 
/**
 * Loopback port the engine serves on.
 */
port: number; 
/**
 * The last start error, if the most recent start attempt failed.
 */
error: string | null }
/**
 * One file that couldn't be registered, and why.
 */
export type LocalModelFailure = { path: string; 
/**
 * User-facing explanation, e.g. that the file is a vision projector rather
 * than a model in its own right.
 */
message: string }
/**
 * Result of registering a batch of picked files.
 * 
 * Deliberately not a plain `Result`: the picker is multi-select, and one
 * unusable file among five shouldn't discard the other four. The UI reports
 * what landed and what didn't.
 */
export type LocalModelImport = { added: ModelInfo[]; failed: LocalModelFailure[] }
export type LogLevel = "trace" | "debug" | "info" | "warn" | "error"
/**
 * How sure we are about a remembered fact. Facts the user stated explicitly
 * are `High`; facts the model inferred from dictations are `Low`. Feeds
 * pruning (low-confidence notes fade first) and injection ordering.
 */
export type MemoryConfidence = "low" | "medium" | "high"
/**
 * How much memory to inject per cleanup pass — a token-budget dial. `Light`
 * keeps only the summary; `Balanced` adds a few relevant notes; `Detailed`
 * adds more. Keeps memory cost flat regardless of how much has been learned.
 */
export type MemoryDetail = "light" | "balanced" | "detailed"
/**
 * A single durable fact SpeakoFlow has learned (or been told) about the user.
 * Notes are pulled into a cleanup pass by relevance, within a character budget
 * — never all at once — and are fully user-editable in Settings → Memory.
 */
export type MemoryNote = { 
/**
 * Stable identifier for edit/delete.
 */
id: string; 
/**
 * The fact itself, as a short canonical statement ("Prefers metric units").
 */
text: string; 
/**
 * ISO date (YYYY-MM-DD) the note was created or last confirmed. Drives
 * recency ordering and decay.
 */
updated?: string; 
/**
 * How reliable the note is.
 */
confidence?: MemoryConfidence; 
/**
 * Where the note came from: `"user"` (typed/dictated explicitly) or
 * `"auto"` (distilled from past dictations). Purely informational.
 */
source?: string }
export type ModelInfo = { id: string; name: string; description: string; filename: string; url: string | null; sha256: string | null; size_mb: number; is_downloaded: boolean; is_downloading: boolean; partial_size: number; is_directory: boolean; engine_type: EngineType; accuracy_score: number; speed_score: number; supports_translation: boolean; supports_streaming: boolean; is_recommended: boolean; 
/**
 * Overall recommendation rank (1 = top); `None` when unranked. Mirrors the
 * GGUF catalog `recommended_rank` and drives the model-list ordering.
 */
recommended_rank: number | null; supported_languages: string[]; supports_language_selection: boolean; is_custom: boolean; 
/**
 * True for a model fine-tuned specifically for dictation cleanup (see
 * [`is_cleanup_specialist`]). The cleanup catalog features these and the
 * settings UI recommends leaving the prompt layers alone for them; the
 * assistant catalog hides them, because a cleanup fine-tune cannot chat.
 */
is_cleanup_specialist?: boolean; 
/**
 * Absolute path to a model the user already had on disk, outside the app's
 * own models directory — either a file they picked or one found in a linked
 * folder. `None` for every managed model, which resolves to
 * `<models_dir>/<filename>` as before.
 * 
 * Set means "this file is not ours": it is never downloaded, never moved,
 * and never deleted. [`ModelManager::delete_model`] only forgets the path.
 */
local_path: string | null; 
/**
 * The linked folder this model was discovered in, when it came from a
 * folder scan rather than an individually picked file. This is what
 * separates "unlink the whole folder" from "remove just this entry", and it
 * lets the UI show where an entry came from.
 */
local_folder: string | null }
export type ModelLoadStatus = { is_loaded: boolean; current_model: string | null }
export type ModelUnloadTimeout = "never" | "immediately" | "min_2" | "min_5" | "min_10" | "min_15" | "hour_1" | "sec_15"
export type OrtAcceleratorSetting = "auto" | "cpu" | "cuda" | "directml" | "rocm"
export type OverlayPosition = "none" | "top" | "bottom"
/**
 * How the recording overlay presents itself while active.
 * `Auto` follows the model: Live when the selected model supports live
 * streaming transcription, otherwise Minimal — the user can override to a
 * concrete choice. `None` shows nothing, `Minimal` is the compact pill, and
 * `Live` is the enlarged readable card (running transcript).
 */
export type OverlayStyle = "auto" | "none" | "minimal" | "live"
export type PaginatedHistory = { entries: HistoryEntry[]; has_more: boolean }
export type PasteMethod = "ctrl_v" | "direct" | "none" | "shift_insert" | "ctrl_shift_v" | "external_script"
export type PermissionAccess = "allowed" | "denied" | "unknown"
export type PostProcessConfigSource = "dedicated_cleanup_selection"
export type PostProcessProvider = { id: string; label: string; base_url: string; allow_base_url_edit?: boolean; models_endpoint?: string | null; supports_structured_output?: boolean }
export type PostProcessReadiness = { state: "ready"; source: PostProcessConfigSource; provider_id: string; provider_label: string; model: string } | { state: "unavailable"; reason: PostProcessUnavailableReason; source: PostProcessConfigSource | null; provider_id: string | null; provider_label: string | null }
/**
 * Optional built-in writing style applied during dictation cleanup.
 * 
 * This enum remains persisted for backwards compatibility. New code selects a
 * built-in or custom style through `post_process_selected_tone_id`; when that
 * field is absent, migration uses this legacy value.
 */
export type PostProcessTone = "none" | "formal" | "casual" | "professional" | "friendly" | "concise"
export type PostProcessUnavailableReason = "no_providers" | "selected_provider_missing" | "no_model_configured" | "no_prompt_selected" | "selected_prompt_missing" | "selected_prompt_empty" | "missing_api_key"
/**
 * A dictation profile: one switch that carries a whole AI-cleanup setup.
 * 
 * Upstream shipped these as assistant personas ("characters") for the floating
 * chat panel. This build has no panel, so a profile does the job that actually
 * matters for dictation: it bundles the cleanup prompt template, the tone, an
 * extra instruction layer, and whether personal memory is injected — so
 * switching from "work email" to "chat message" is one choice instead of
 * three separate settings.
 * 
 * Built-ins ship with the app; users can add, edit, duplicate, import, and
 * delete their own. The `default` profile can never be deleted.
 */
export type Profile = { 
/**
 * Stable identifier. `"default"` is reserved for the non-deletable base
 * profile.
 */
id: string; 
/**
 * Display name shown in the picker and the tray.
 */
name: string; 
/**
 * Extra style/context instructions layered onto the cleanup prompt (after
 * the tone directive, before the output contract). Empty adds nothing.
 */
instructions?: string; 
/**
 * Which cleanup prompt template this profile selects. Empty keeps whatever
 * `post_process_selected_prompt_id` is set to globally.
 */
prompt_id?: string; 
/**
 * Built-in tone id or a `CustomPostProcessTone.id` applied on top of the
 * prompt. Empty keeps the global `post_process_selected_tone_id`.
 */
tone_id?: string; 
/**
 * Whether personal memory is injected while this profile is active. Off
 * for profiles where the user's personal context is irrelevant.
 */
use_memory?: boolean; 
/**
 * Optional avatar as a `data:image/...;base64,...` URL (empty → initial).
 */
avatar?: string; 
/**
 * True for profiles shipped with the app. Built-ins may be edited or
 * duplicated; only `default` is protected from deletion.
 */
builtin?: boolean; 
/**
 * One-line subtitle shown on the profile card (e.g. "Short, direct
 * answers"). Purely cosmetic — it never reaches the model.
 */
description?: string }
export type RecordingRetentionPeriod = "never" | "preserve_limit" | "days_3" | "weeks_2" | "months_3"
/**
 * A single deterministic find/replace rule applied to the transcript.
 * 
 * Rules run as a fast, offline, deterministic pass that complements (does not
 * duplicate) the optional LLM post-processing. `search` is matched literally
 * by default; set `is_regex` to treat it as a regular expression. `replace`
 * may contain magic commands such as `[date]`, `[time]`, `[uppercase]`,
 * `[lowercase]`, `[capitalize]`, and `[nospace]`.
 */
export type Replacement = { 
/**
 * Text (or regex pattern when `is_regex` is set) to search for.
 */
search: string; 
/**
 * Replacement text. Supports the magic commands described on the struct.
 */
replace: string; 
/**
 * Treat `search` as a regular expression instead of a literal string.
 */
is_regex?: boolean; 
/**
 * Whether this rule is applied. Disabled rules are kept but skipped.
 */
enabled?: boolean; 
/**
 * Remove whitespace immediately before each match.
 */
trim_before?: boolean; 
/**
 * Remove whitespace immediately after each match.
 */
trim_after?: boolean; 
/**
 * Case transform applied to this rule's output.
 */
capitalization?: Capitalization }
export type SecretMap = Partial<{ [key in string]: string }>
export type ShortcutBinding = { id: string; name: string; description: string; default_binding: string; current_binding: string }
export type SoundTheme = 
/**
 * SpeakoFlow's own start/stop cues — the default. Ships a matching lock
 * cue (`popo_lock.wav`) used by every theme for tap-to-lock.
 */
"dictation" | "marimba" | "pop" | "click" | "custom"
/**
 * UI appearance preference. `System` follows the OS; `Light` / `Dark` pin the
 * theme regardless of the OS setting. Serialized lowercase ("light", "dark",
 * "system") to match the `data-theme` attribute the frontend sets on <html>.
 */
export type Theme = "light" | "dark" | "system"
export type TypingTool = "auto" | "wtype" | "kwtype" | "dotool" | "ydotool" | "xdotool"
/**
 * UI text size for the main window. Applied as a webview zoom factor so the
 * whole interface scales together. Serialized snake_case ("small", "default",
 * "large", "extra_large") to match the values the settings dropdown uses.
 */
export type UiTextSize = "small" | "default" | "large" | "extra_large"
/**
 * The user's personal, local-first memory: a short always-on "About You"
 * summary plus a list of durable notes. Stored on-device in settings and
 * injected (in part) into an AI-cleanup pass only when `memory_enabled` is on,
 * incognito is off, and the active profile opts in.
 */
export type UserMemory = { 
/**
 * The always-on summary injected into every reply (kept to a few
 * sentences). Empty until the user or a distillation pass fills it.
 */
about_you?: string; 
/**
 * Durable facts, selected by relevance within the detail budget.
 */
notes?: MemoryNote[] }
export type WhisperAcceleratorSetting = "auto" | "cpu" | "gpu"
export type WindowsMicrophonePermissionStatus = { supported: boolean; overall_access: PermissionAccess; device_access: PermissionAccess; app_access: PermissionAccess; desktop_app_access: PermissionAccess }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
